# Generated by Django 5.2 on 2026-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_watch_time', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('highest_streak', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_streak', '-total_watch_time'],
            },
        ),
    ]
